const foodData = [
  {
    menuId: 1,
    name: "Crispy Chicken Burger",
    photo: images.crispy_chicken_burger,
    description: "Burger with crispy chicken, cheese and lettuce",
    calories: 200,
    price: 10,
    merchant: "ByProgrammers Burger",
    rating: 4.8,
    categories: "burger",
    priceRating: affordable,
    restaurenPhoto: images.burger_merchant_1,
    duration: "30 - 45 min",
    location: {
      latitude: 1.5347282806345879,
      longitude: 110.35632207358996,
    },
    courier: {
      avatar: images.avatar_1,
      name: "Amy",
    },
  },
  {
    menuId: 2,
    name: "Crispy Chicken Burger with Honey Mustard",
    photo: images.honey_mustard_chicken_burger,
    description: "Crispy Chicken Burger with Honey Mustard Coleslaw",
    calories: 250,
    price: 15,
    merchant: "ByProgrammers Burger",
    rating: 4.8,
    categories: "burger",
    priceRating: affordable,
    restaurenPhoto: images.burger_merchant_1,
    duration: "30 - 45 min",
    location: {
      latitude: 1.5347282806345879,
      longitude: 110.35632207358996,
    },
    courier: {
      avatar: images.avatar_1,
      name: "Amy",
    },
  },
  {
    menuId: 3,
    name: "Crispy Baked French Fries",
    photo: images.baked_fries,
    description: "Crispy Baked French Fries",
    calories: 194,
    price: 8,
    merchant: "ByProgrammers Burger",
    rating: 4.8,
    categories: "chips",
    priceRating: affordable,
    restaurenPhoto: images.burger_merchant_1,
    duration: "30 - 45 min",
    location: {
      latitude: 1.5347282806345879,
      longitude: 110.35632207358996,
    },
    courier: {
      avatar: images.avatar_1,
      name: "Amy",
    },
  },
  {
    menuId: 4,
    name: "Hawaiian Pizza",
    photo: images.hawaiian_pizza,
    description: "Canadian bacon, homemade pizza crust, pizza sauce",
    calories: 250,
    price: 15,
    merchant: "ByProgrammers Pizza",
    rating: 4.8,
    categories: "pizza",
    priceRating: affordable,
    restaurenPhoto: images.pizza_merchant,
    duration: "30 - 45 min",
    location: {
      latitude: 1.556306570595712,
      longitude: 110.35504616746915,
    },
    courier: {
      avatar: images.avatar_2,
      name: "Jackson",
    },
  },
  {
    menuId: 5,
    name: "Tomato & Basil Pizza",
    photo: images.pizza,
    description: "Fresh tomatoes, aromatic basil pesto and melted bocconcini",
    calories: 250,
    price: 20,
    merchant: "ByProgrammers Pizza",
    rating: 4.8,
    categories: "pizza",
    priceRating: affordable,
    restaurenPhoto: images.pizza_merchant,
    duration: "30 - 45 min",
    location: {
      latitude: 1.556306570595712,
      longitude: 110.35504616746915,
    },
    courier: {
      avatar: images.avatar_2,
      name: "Jackson",
    },
  },
  {
    menuId: 6,
    name: "Tomato Pasta",
    photo: images.tomato_pasta,
    description: "Pasta with fresh tomatoes",
    calories: 100,
    price: 10,
    merchant: "ByProgrammers Pizza",
    rating: 4.8,
    categories: "pasta",
    priceRating: affordable,
    restaurenPhoto: images.pizza_merchant,
    duration: "30 - 45 min",
    location: {
      latitude: 1.556306570595712,
      longitude: 110.35504616746915,
    },
    courier: {
      avatar: images.avatar_2,
      name: "Jackson",
    },
  },
  {
    menuId: 7,
    name: "Mediterranean Chopped Salad ",
    photo: images.salad,
    description: "Finely chopped lettuce, tomatoes, cucumbers",
    calories: 100,
    price: 10,
    merchant: "ByProgrammers Pizza",
    rating: 4.8,
    categories: "salad",
    priceRating: affordable,
    restaurenPhoto: images.pizza_merchant,
    duration: "30 - 45 min",
    location: {
      latitude: 1.556306570595712,
      longitude: 110.35504616746915,
    },
    courier: {
      avatar: images.avatar_2,
      name: "Jackson",
    },
  },
  {
    menuId: 8,
    name: "Chicago Style Hot Dog",
    photo: images.chicago_hot_dog,
    description: "Fresh tomatoes, all beef hot dogs",
    calories: 100,
    price: 20,
    merchant: "ByProgrammers Hotdogs",
    rating: 4.8,
    categories: "hotdog",
    priceRating: expensive,
    restaurenPhoto: images.hot_dog_merchant,
    duration: "20 - 25 min",
    location: {
      latitude: 1.5238753474714375,
      longitude: 110.34261833833622,
    },
    courier: {
      avatar: images.avatar_3,
      name: "James",
    },
  },

  {
    menuId: 9,
    name: "Sushi sets",
    photo: images.sushi,
    description: "Fresh salmon, sushi rice, fresh juicy avocado",
    calories: 100,
    price: 50,
    merchant: "ByProgrammers Sushi",
    rating: 4.8,
    categories: "sushi",
    priceRating: expensive,
    restaurenPhoto: images.japanese_merchant,
    duration: "10 - 15 min",
    location: {
      latitude: 1.5578068150528928,
      longitude: 110.35482523764315,
    },
    courier: {
      avatar: images.avatar_4,
      name: "Ahmad",
    },
  },

  {
    menuId: 10,
    name: "Kolo Mee",
    photo: images.kolo_mee,
    description: "Noodles with char siu",
    calories: 200,
    price: 5,
    merchant: "ByProgrammers Cuisine",
    rating: 4.8,
    categories: "cuisine",
    priceRating: expensive,
    restaurenPhoto: images.noodle_shop,
    duration: "15 - 20 min",
    location: {
      latitude: 1.558050496260768,
      longitude: 110.34743759630511,
    },
    courier: {
      avatar: images.avatar_4,
      name: "Muthu",
    },
  },
  {
    menuId: 11,
    name: "Sarawak Laksa",
    photo: images.sarawak_laksa,
    description: "Vermicelli noodles, cooked prawns",
    calories: 300,
    price: 8,
    merchant: "ByProgrammers Cuisine",
    rating: 4.8,
    categories: "cuisine",
    priceRating: expensive,
    restaurenPhoto: images.noodle_shop,
    duration: "15 - 20 min",
    location: {
      latitude: 1.558050496260768,
      longitude: 110.34743759630511,
    },
    courier: {
      avatar: images.avatar_4,
      name: "Muthu",
    },
  },
];